pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
]

radiofm/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import PauloContruções, login_requirido, CadastroClienteView, Contrato, ListCliente, OpcoesPag, PagamentoAprovado, CreateAssinatura, Finalizacao, ListFinal, PagamentoProcessando
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
    path("", include("pages.urls", namespace="pages")),
    path("divulgacao1/", PauloContruções.as_view(), name="divulgação"),
    path('requerid/', views.login_requirido, name="burlar_login"),
    path('add-cliente/', CadastroClienteView.as_view(), name='add-cliente'),
    path('contrato/', Contrato.as_view(), name='contrato'),
    path('list-cliente/', ListCliente.as_view(), name='listar-cliente'),
    path('opçoes-pagamento/', OpcoesPag.as_view(), name='opc-pagamento'),
    path('pagamento-aprovado/', PagamentoAprovado.as_view(), name='pag-aproved'),
    path('create-assinatura/', CreateAssinatura.as_view(), name='create-final'),
    path('finalizacao/', Finalizacao.as_view(), name='final'),
    path('list-final/', ListFinal.as_view(), name='list-final'),
    path('pagamento-process/', PagamentoProcessando.as_view(), name='pag-process'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
# Create your models here.


class ClientePlano(models.Model):
    plano = models.CharField(verbose_name='Plano: ', max_length=100, blank=True, null=True)
    descri = models.CharField(verbose_name='Descrição: ', max_length=100, blank=True, null=True)

    def __str__(self):
            return "{}".format(self.plano)


class CadastroCliente(models.Model):
    nome_cliente = models.CharField(verbose_name='Nome: ', max_length=60, null=True, blank=True)
    data_assinatura = models.DateTimeField(verbose_name='Data da Assinatura: ', null=False)
    plano_escolhido = models.ForeignKey(ClientePlano, max_length=100, null=True, on_delete=models.PROTECT)
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
            return "{}".format(self.plano_escolhido)


class CadastroFinal(models.Model):
    nome = models.CharField(verbose_name='Nome: ', max_length=60, null=False)
    data = models.DateTimeField(verbose_name='Data: ', null=False)
    endereco = models.CharField(verbose_name='Endereço: ', max_length=150, null=False)
    contato = models.CharField(verbose_name='Telefone: ', max_length=150, null=False)
    plano_solicitado = models.ForeignKey(ClientePlano, max_length=100, null=True, on_delete=models.PROTECT)

    def __str__(self):
            return "{}".format(self.nome)

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "home.html"

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.template.loader import get_template
from .models import CadastroCliente, CadastroFinal

# Create your views here.


#TemplateView

class PauloContruções(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('burlar_login')
    template_name = 'paulo.html'


def login_requirido(request):
    return render(request, 'requerid.html')


class CadastroClienteView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('burlar_login')
    model = CadastroCliente
    fields = ['nome_cliente', 'data_assinatura', 'plano_escolhido']
    template_name = 'create.html'
    success_url = ('/opçoes-pagamento')

    def form_valid(self, form):

        form.instance.usuario = self.request.user

        url = super().form_valid(form)

        return url



class Contrato(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('burlar_login')
    template_name = 'contrato.html'


class ListCliente(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('burlar_login')
    model = CadastroCliente
    template_name = 'list-cliente.html'

    def get_queryset(self):
        self.object_list = CadastroCliente.objects.filter(usuario=self.request.user)
        return self.object_list


class OpcoesPag(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('burlar_login')
    template_name = 'pagamento.html'


class PagamentoAprovado(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('burlar_login')
    template_name = 'pagamento-aprovado.html'


class PagamentoProcessando(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('burlar_login')
    template_name = 'pagamento-process.html'


class CreateAssinatura(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('burlar_login')
    model = CadastroFinal
    fields = ['nome', 'data', 'endereco', 'contato', 'plano_solicitado']
    template_name = 'create.html'
    success_url = ('/finalizacao')


class Finalizacao(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('burlar_login')
    template_name = 'final.html'


class ListFinal(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('burlar_login')
    model = CadastroFinal
    template_name = 'list-final.html'

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">Rádio FM Litoral</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

templates/contrato.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CONTRATO</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Font-awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Select2 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'pages:home' %}">Rádio Litoral FM</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
                <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                    <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                    </ul>
                        <ul class="navbar-nav px-3">
                            <li class="nav-item text-nowrap">
                                <a href="{% url 'account_logout' %}" class="nav-link">Sair</a>
                            </li>
                    </ul>
                    {% else %}
                    </ul>
                        <ul class="navbar-nav px-3">
                        <li class="nav-item">
                            <a href="{% url 'account_login' %}" class="nav-link">Entrar</a>
                        </li>
                    </ul>
                        <ul class="navbar-nav px-3">
                        <li class="nav-item">
                            <a href="{% url 'account_signup' %}" class="nav-link">Cadastrar</a>
                        </li>
                    </ul>
                    {% endif %}
            </div>
    </nav>
</head>
<body>
    <style>
        main{
            background-color: white;
                width: auto;
                heigth: 600px;
                margin-left: 35px;
                margin-right: 35px;
                padding: 15px;
                box-shadow: 6px 6px 10px black;
                font-family: Arial, Helvetica, sans-serif;
                font-size: 25px;
                border-radius: 15px;
                color: black;
            }
        body{
            background-color: rgb(60, 117, 202);
    
        }
        </style>
        
    
        <br><br><br>
        <main style="margin-top: 30px;">
            <h1 style="font-weight: bold;">CONTRATO</h1> <br>
            <p>Aqui ficará o contrato!...</p>
            <br><br>
            <a href="/add-cliente"><button type="button" class="btn btn-primary">Aceito</button></a>
            <a href="/"><button type="button" class="btn btn-primary">Não Aceito</button></a>
        </main>
    <br><br><br><br>
    
    <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <!-- Select2 -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    </body>
    </html>
</body>
</html>

templates/create.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criar</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Font-awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Select2 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'pages:home' %}">Rádio Litoral FM</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
                <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                    <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                    </ul>
                        <ul class="navbar-nav px-3">
                            <li class="nav-item text-nowrap">
                                <a href="{% url 'account_logout' %}" class="nav-link">Sair</a>
                            </li>
                    </ul>
                    {% else %}
                    </ul>
                        <ul class="navbar-nav px-3">
                        <li class="nav-item">
                            <a href="{% url 'account_login' %}" class="nav-link">Entrar</a>
                        </li>
                    </ul>
                        <ul class="navbar-nav px-3">
                        <li class="nav-item">
                            <a href="{% url 'account_signup' %}" class="nav-link">Cadastrar</a>
                        </li>
                    </ul>
                    {% endif %}
            </div>
    </nav>
</head>
<body>
    <style>
        main{
            background-color: white;
            heigth: 600px;
            width: auto;
            margin-left: 30px;
            margin-right: 30px;
            padding: 20px;
            box-shadow: 6px 6px 10px black;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 20px;
            border-radius: 15px;
            color: black;
            text-align: left;
            }
        body{
            background-color: rgb(60, 117, 202);
    
        }
        </style>
        
    
        <br><br><br>
        <main style="margin-top: 30px;">
            <form action="" method="POST">
                
                {% csrf_token %} 
    
                {{ form|crispy }}
                <br>
                <button type="submit" class="btn btn-success">Criar</button>
    
            </form>
            <br>
            <a href="/"><button class="btn btn-danger">Cancelar</button></a>
        </main>
    <br><br><br><br>
    
    <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <!-- Select2 -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    </body>
    </html>
</body>
</html>

templates/final.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Finalização</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Font-awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Select2 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'pages:home' %}">Rádio Litoral FM</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
                <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                    <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                    </ul>
                        <ul class="navbar-nav px-3">
                            <li class="nav-item text-nowrap">
                                <a href="{% url 'account_logout' %}" class="nav-link">Sair</a>
                            </li>
                    </ul>
                    {% else %}
                    </ul>
                        <ul class="navbar-nav px-3">
                        <li class="nav-item">
                            <a href="{% url 'account_login' %}" class="nav-link">Entrar</a>
                        </li>
                    </ul>
                        <ul class="navbar-nav px-3">
                        <li class="nav-item">
                            <a href="{% url 'account_signup' %}" class="nav-link">Cadastrar</a>
                        </li>
                    </ul>
                    {% endif %}
            </div>
    </nav>
</head>
<body>
<style>
    body{
        background-color: rgb(32, 127, 235);
    }
    main{
        width: auto;
        height: 300px;
        border-radius: 5px;
        box-shadow: 3px 2px 2px rgb(47, 48, 47);
        margin-left: 30px;
        margin-right: 30px;
        padding: 10px;
        background-color: white;
    }
</style>
    <br><br><br><br>
    <main>
        <h1 style="font-weight: bold;">Finalização</h1>
        <hr>
        <p style="font-weight: bold;">Seu pedido foi Concluido! <br>
        Clique no botão abaixo para entrar em contato com um de nossos Atendentes pelo WhatsApp <br>
        Lá, você resolverá os detalhes finais conosco!</p>
        <a href="http://wa.me/5571996579421" target="__blank"><button type="button" class="btn btn-success">Clique Aqui!</button></a>
    </main>
    <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <!-- Select2 -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    </body>
    </html>
</body>
</html>

templates/list-cliente.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CONTRATO</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Font-awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Select2 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'pages:home' %}">Rádio Litoral FM</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
                <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                    <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                    </ul>
                        <ul class="navbar-nav px-3">
                            <li class="nav-item text-nowrap">
                                <a href="{% url 'account_logout' %}" class="nav-link">Sair</a>
                            </li>
                    </ul>
                    {% else %}
                    </ul>
                        <ul class="navbar-nav px-3">
                        <li class="nav-item">
                            <a href="{% url 'account_login' %}" class="nav-link">Entrar</a>
                        </li>
                    </ul>
                        <ul class="navbar-nav px-3">
                        <li class="nav-item">
                            <a href="{% url 'account_signup' %}" class="nav-link">Cadastrar</a>
                        </li>
                    </ul>
                    {% endif %}
            </div>
    </nav>
</head>
<body>
    <style>
        main{
            background-color: white;
                width: auto;
                heigth: 600px;
                margin-left: 20px;
                margin-right: 20px;
                padding: 15px;
                box-shadow: 6px 6px 10px black;
                font-family: Arial, Helvetica, sans-serif;
                font-size: 25px;
                border-radius: 15px;
                color: black;
            }
        body{
            background-color: rgb(60, 117, 202);
    
        }
        </style>
        
    
        <br><br><br><br><br>
        {% for CadastroCliente in object_list %}
        <main>
            <h3 style="font-weight: bold; text-align: left; font-size: 40px;">Serviço: {{ CadastroCliente.plano_escolhido }}</h3>
            <hr>
            <h3 style="font-weight: bold; text-align: left;">Nome: {{ CadastroCliente.nome_cliente }}</h3>
            <h3 style="font-weight: bold; text-align: left;">Data: {{ CadastroCliente.data_assinatura }}</h3> <br>
        </main>
        <br>
        {% empty %}
            <main>
                <h1 style="font-weight: bold;">Nenhuma Assinatura Encontrada!</h1>
                <hr>
                <p style="font-weight: bold; font-size: 25px;">Faça sua primeira assinatura com nossa rádio, <br>
                    Para que elas possam ficar visíveis aqui!</p>
            </main>
            <hr>
        {% endfor %}
    <br><br><br><br>
    
    <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <!-- Select2 -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    </body>
    </html>
</body>
</html>

templates/paulo.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <title>Paulo Contruções</title>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'pages:home' %}">Rádio Litoral FM</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
                <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                    <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                    </ul>
                        <ul class="navbar-nav px-3">
                            <li class="nav-item text-nowrap">
                                <a href="{% url 'account_logout' %}" class="nav-link">Sair</a>
                            </li>
                    </ul>
                    {% else %}
                    </ul>
                        <ul class="navbar-nav px-3">
                        <li class="nav-item">
                            <a href="{% url 'account_login' %}" class="nav-link">Entrar</a>
                        </li>
                    </ul>
                        <ul class="navbar-nav px-3">
                        <li class="nav-item">
                            <a href="{% url 'account_signup' %}" class="nav-link">Cadastrar</a>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </nav>
</head>
<body>
<br><br><br><br>
    <style>
        body{
            background-color: rgb(241, 232, 214);
            color: black;
        }
        h1{
            margin-left: 20px;
        }
        p{
            margin-left: 20px;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 30px;
            font-weight: bold;
        }
    </style>
    <h1>Paulo Contruções!</h1>
    <hr>
    <p>
        Prezamos pela qualidade do serviço <br>
        E sobre tudo a satisfação do cliente! <br>
        E então, Oque está esperando? <br>
        Faça seu orçamento <a href="http://wa.me/5571982758140" target="__blank"><strong>JÁ!</strong> <br></a>
        <a href="http://wa.me/5571982758140" target="__blank"><button type="button" class="btn btn-primary"><strong>Faça Já Seu Oraçamento!</strong></button> </a>
    </p>
<br><br>
</body>
</html>